//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CookIt.Resources.strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Ingredients {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Ingredients() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CookIt.Resources.strings.Ingredients", typeof(Ingredients).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baking powder.
        /// </summary>
        internal static string BakingPowder {
            get {
                return ResourceManager.GetString("BakingPowder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baking soda.
        /// </summary>
        internal static string BakingSoda {
            get {
                return ResourceManager.GetString("BakingSoda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blueberries.
        /// </summary>
        internal static string Blueberries {
            get {
                return ResourceManager.GetString("Blueberries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Butter.
        /// </summary>
        internal static string Butter {
            get {
                return ResourceManager.GetString("Butter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chocolate.
        /// </summary>
        internal static string Chocolate {
            get {
                return ResourceManager.GetString("Chocolate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cocoa.
        /// </summary>
        internal static string Cocoa {
            get {
                return ResourceManager.GetString("Cocoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coconut milk.
        /// </summary>
        internal static string CoconutMilk {
            get {
                return ResourceManager.GetString("CoconutMilk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cream.
        /// </summary>
        internal static string Cream {
            get {
                return ResourceManager.GetString("Cream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dried tomatoes.
        /// </summary>
        internal static string DriedTomatoes {
            get {
                return ResourceManager.GetString("DriedTomatoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eggs.
        /// </summary>
        internal static string Eggs {
            get {
                return ResourceManager.GetString("Eggs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flour.
        /// </summary>
        internal static string Flour {
            get {
                return ResourceManager.GetString("Flour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garlic.
        /// </summary>
        internal static string Garlic {
            get {
                return ResourceManager.GetString("Garlic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MapleSirup.
        /// </summary>
        internal static string MapleSyrup {
            get {
                return ResourceManager.GetString("MapleSyrup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milk.
        /// </summary>
        internal static string Milk {
            get {
                return ResourceManager.GetString("Milk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Millet.
        /// </summary>
        internal static string Millet {
            get {
                return ResourceManager.GetString("Millet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minced meat.
        /// </summary>
        internal static string MincedMeat {
            get {
                return ResourceManager.GetString("MincedMeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oil.
        /// </summary>
        internal static string Oil {
            get {
                return ResourceManager.GetString("Oil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OliveOil.
        /// </summary>
        internal static string OliveOil {
            get {
                return ResourceManager.GetString("OliveOil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olives.
        /// </summary>
        internal static string Olives {
            get {
                return ResourceManager.GetString("Olives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oregano.
        /// </summary>
        internal static string Oregano {
            get {
                return ResourceManager.GetString("Oregano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parmesan.
        /// </summary>
        internal static string Parmesan {
            get {
                return ResourceManager.GetString("Parmesan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsley.
        /// </summary>
        internal static string Parsley {
            get {
                return ResourceManager.GetString("Parsley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasta.
        /// </summary>
        internal static string Pasta {
            get {
                return ResourceManager.GetString("Pasta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pork chop.
        /// </summary>
        internal static string PorkChop {
            get {
                return ResourceManager.GetString("PorkChop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powdered sugar.
        /// </summary>
        internal static string PowderedSugar {
            get {
                return ResourceManager.GetString("PowderedSugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoked salmon.
        /// </summary>
        internal static string SmokedSalmon {
            get {
                return ResourceManager.GetString("SmokedSalmon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soy sauce.
        /// </summary>
        internal static string SoySauce {
            get {
                return ResourceManager.GetString("SoySauce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuna.
        /// </summary>
        internal static string Tuna {
            get {
                return ResourceManager.GetString("Tuna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water.
        /// </summary>
        internal static string Water {
            get {
                return ResourceManager.GetString("Water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wine.
        /// </summary>
        internal static string Wine {
            get {
                return ResourceManager.GetString("Wine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zucchini.
        /// </summary>
        internal static string Zucchini {
            get {
                return ResourceManager.GetString("Zucchini", resourceCulture);
            }
        }
    }
}
